<<<<<<< HEAD
version: '3.8'
=======
>>>>>>> iter2
services:
  # MongoDB (Document Store)
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: movie_db

  # Neo4j (Graph Database)
  neo4j:
    image: neo4j:latest
    ports:
      - "7474:7474" # Interface web
      - "7687:7687" # Protocole Bolt
    environment:
      NEO4J_AUTH: neo4j/password123

  # Redis (Key-Value Store)
  redis:
    image: redis:latest
    ports:
<<<<<<< HEAD
      - "6379:6379"
=======
      - "6379:6379"

  # HBase (Column Database)
  hbase:
    image: dajobe/hbase
    ports:
      - "16000:16000"
      - "9090:9090"  # Thrift API
      - "16010:16010" # Web UI
    environment:
      - HBASE_MANAGES_ZK=true
>>>>>>> iter2
